// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure.Persistence;

#nullable disable

namespace Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SessionGuardDbContext))]
    partial class SessionGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Server.Infrastructure.Persistence.AgentEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPolicyVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsageReportAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalUser")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId");

                    b.HasIndex("ChildId");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Server.Infrastructure.Persistence.ChildEntity", b =>
                {
                    b.Property<string>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyLimitMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ChildId");

                    b.ToTable("Children", (string)null);
                });

            modelBuilder.Entity("Server.Infrastructure.Persistence.UsageReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UsageDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "UsageDateUtc")
                        .IsUnique();

                    b.ToTable("UsageReports", (string)null);
                });

            modelBuilder.Entity("Server.Infrastructure.Persistence.AgentEntity", b =>
                {
                    b.HasOne("Server.Infrastructure.Persistence.ChildEntity", "Child")
                        .WithMany("Agents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Server.Infrastructure.Persistence.UsageReportEntity", b =>
                {
                    b.HasOne("Server.Infrastructure.Persistence.AgentEntity", "Agent")
                        .WithMany("UsageReports")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Server.Infrastructure.Persistence.AgentEntity", b =>
                {
                    b.Navigation("UsageReports");
                });

            modelBuilder.Entity("Server.Infrastructure.Persistence.ChildEntity", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
